const G={score:Number(localStorage.getItem('sobrizen-game-score')||0),memory:null,reaction:null,taps:null};
const save=()=>{try{localStorage.setItem('sobrizen-game-score',String(G.score))}catch{}};
export function gamesView(){return `<div class="greeting"><span class="eyebrow">PASSE L’ENVIE</span><h1>Occupe ton esprit quelques minutes.</h1><p class="muted">Des mini-jeux simples pour traverser un moment d’ennui ou détourner ton attention. Ils ne remplacent pas une aide médicale.</p></div><div class="game-score"><span>✦ Points détente</span><b id="gameScore">${G.score}</b></div><div class="game-grid"><button class="game-card" data-game="memory"><span>🧠</span><b>Memory</b><small>Retrouve les 6 paires</small></button><button class="game-card" data-game="reaction"><span>⚡</span><b>Réflexe Zen</b><small>Teste ta concentration</small></button><button class="game-card" data-game="taps"><span>🎯</span><b>Défi 20 secondes</b><small>Attrape la cible</small></button><button class="game-card" data-game="ground"><span>🌿</span><b>5 choses</b><small>Mini défi d’ancrage</small></button></div><section id="gameZone" class="card game-zone"><span class="eyebrow">CHOISIS UNE ACTIVITÉ</span><h2>Une envie ? Donne-toi quelques minutes.</h2><p>Choisis un jeu ci-dessus. Tu peux arrêter quand tu veux et revenir à ton parcours sans perdre tes données.</p></section>`}

function zone(){return document.querySelector('#gameZone')}
function add(n){G.score+=n;save();const el=document.querySelector('#gameScore');if(el)el.textContent=G.score}
function memory(){const icons=['🌱','☀️','🌊','🍃','🌙','⭐'];const cards=[...icons,...icons].sort(()=>Math.random()-.5);G.memory={open:[],done:new Set(),moves:0};zone().innerHTML=`<span class="eyebrow">MEMORY</span><div class="row between"><h2>Retrouve les paires</h2><span class="tag" id="moves">0 coups</span></div><div class="memory-grid">${cards.map((x,i)=>`<button class="memory-card" data-mi="${i}" data-icon="${x}" aria-label="Carte ${i+1}">?</button>`).join('')}</div><p class="small">Chaque partie terminée rapporte 20 points détente.</p>`}
function memoryPick(btn){const m=G.memory,i=Number(btn.dataset.mi);if(!m||m.done.has(i)||m.open.includes(i)||m.open.length>=2)return;btn.textContent=btn.dataset.icon;btn.classList.add('open');m.open.push(i);if(m.open.length===2){m.moves++;document.querySelector('#moves').textContent=m.moves+' coups';const [a,b]=m.open,els=[...document.querySelectorAll('.memory-card')];if(els[a].dataset.icon===els[b].dataset.icon){m.done.add(a);m.done.add(b);m.open=[];els[a].classList.add('matched');els[b].classList.add('matched');if(m.done.size===els.length){add(20);setTimeout(()=>zone().insertAdjacentHTML('beforeend','<div class="game-win"><b>Partie terminée ✦ +20 points</b><button class="secondary" data-game="memory">Rejouer</button></div>'),250)}}else setTimeout(()=>{els[a].textContent='?';els[b].textContent='?';els[a].classList.remove('open');els[b].classList.remove('open');m.open=[]},650)}}
function reaction(){G.reaction={ready:false,start:0,timer:null};zone().innerHTML='<span class="eyebrow">RÉFLEXE ZEN</span><h2>Attends le signal…</h2><p>Quand la zone devient prête, touche-la le plus vite possible.</p><button id="reactionPad" class="reaction-pad">Attends…</button>';const wait=1000+Math.random()*3000;G.reaction.timer=setTimeout(()=>{G.reaction.ready=true;G.reaction.start=performance.now();const p=document.querySelector('#reactionPad');if(p){p.classList.add('ready');p.textContent='TOUCHE !'}},wait)}
function reactionHit(){const r=G.reaction;if(!r)return;if(!r.ready){clearTimeout(r.timer);zone().insertAdjacentHTML('beforeend','<p class="game-result">Trop tôt 🙂 Recommence tranquillement.</p>');return}const ms=Math.round(performance.now()-r.start);add(5);zone().innerHTML=`<span class="eyebrow">RÉFLEXE ZEN</span><h2>${ms} ms</h2><p>Bien joué. +5 points détente.</p><button class="secondary" data-game="reaction">Rejouer</button>`;G.reaction=null}
function taps(){G.taps={count:0,end:Date.now()+20000};zone().innerHTML='<span class="eyebrow">DÉFI 20 SECONDES</span><div class="row between"><h2>Attrape la cible</h2><b id="tapTime">20 s</b></div><div class="tap-arena"><button id="tapTarget" class="tap-target" aria-label="Cible">●</button></div><p id="tapCount">0 cible</p>';moveTarget();const tick=setInterval(()=>{if(!G.taps){clearInterval(tick);return}const left=Math.max(0,Math.ceil((G.taps.end-Date.now())/1000)),t=document.querySelector('#tapTime');if(t)t.textContent=left+' s';if(left<=0){clearInterval(tick);const n=G.taps.count;G.taps=null;add(Math.min(20,n));zone().innerHTML=`<span class="eyebrow">TERMINÉ</span><h2>${n} touches</h2><p>Tu viens de consacrer 20 secondes à autre chose. +${Math.min(20,n)} points.</p><button class="secondary" data-game="taps">Rejouer</button>`}},250)}
function moveTarget(){const b=document.querySelector('#tapTarget');if(!b)return;b.style.left=(5+Math.random()*78)+'%';b.style.top=(5+Math.random()*70)+'%'}
function tap(){if(!G.taps)return;G.taps.count++;const c=document.querySelector('#tapCount');if(c)c.textContent=G.taps.count+' touche'+(G.taps.count>1?'s':'');moveTarget()}
function grounding(){zone().innerHTML='<span class="eyebrow">5 CHOSES</span><h2>Regarde autour de toi.</h2><p>Prends ton temps et trouve mentalement :</p><ol class="tool-steps"><li>5 choses que tu peux voir</li><li>4 choses que tu peux toucher</li><li>3 choses que tu peux entendre</li><li>2 choses que tu peux sentir</li><li>1 chose que tu apprécies maintenant</li></ol><button class="primary" data-ground-done>J’ai terminé</button>'}
export function initGames(){document.addEventListener('click',e=>{const game=e.target.closest('[data-game]')?.dataset.game;if(game){if(game==='memory')memory();if(game==='reaction')reaction();if(game==='taps')taps();if(game==='ground')grounding();return}const mc=e.target.closest('.memory-card');if(mc){memoryPick(mc);return}if(e.target.closest('#reactionPad')){reactionHit();return}if(e.target.closest('#tapTarget')){tap();return}if(e.target.closest('[data-ground-done]')){add(10);zone().innerHTML='<span class="eyebrow">BIEN JOUÉ</span><h2>Tu as pris un moment pour revenir au présent.</h2><p>+10 points détente. Tu peux choisir une autre activité ou retourner à ton parcours.</p>'}})}
