const G={score:Number(localStorage.getItem('sobrizen-game-score')||0),memory:null,reaction:null,taps:null,snake:null,blocks:null};
const save=()=>{try{localStorage.setItem('sobrizen-game-score',String(G.score))}catch{}};
const FREE_GAMES=new Set(['snake','blocks','ground']);
const premiumAccess=()=>document.documentElement.dataset.premium==='true';
function gameCard(id,icon,title,detail,premium){const allowed=premium||FREE_GAMES.has(id);return allowed?`<button class="game-card" data-game="${id}"><span>${icon}</span><b>${title}</b><small>${detail}</small></button>`:`<button class="game-card" data-game-upgrade="${id}" aria-label="${title} — réservé à Premium"><span>${icon}</span><b>${title}</b><small>🔒 Premium · ${detail}</small></button>`;}
export function gamesView({premium=false}={}){return `<div class="greeting"><span class="eyebrow">PASSE L’ENVIE</span><h1>Occupe ton esprit quelques minutes.</h1><p class="muted">Le gratuit inclut Snake Zen, Blocs Zen et l’exercice d’ancrage « 5 choses ». Trois mini-jeux supplémentaires sont inclus dans Premium.</p></div><div class="game-score"><span>✦ Points détente</span><b id="gameScore">${G.score}</b></div><div class="game-grid">${gameCard('memory','🧠','Memory','Retrouve les 6 paires',premium)}${gameCard('reaction','⚡','Réflexe Zen','Teste ta concentration',premium)}${gameCard('taps','🎯','Défi 20 secondes','Attrape la cible',premium)}${gameCard('ground','🌿','5 choses','Exercice d’ancrage toujours accessible',premium)}${gameCard('snake','🐍','Snake Zen','Jeu inclus en gratuit',premium)}${gameCard('blocks','🧱','Blocs Zen','Jeu inclus en gratuit',premium)}</div><section id="gameZone" class="card game-zone"><span class="eyebrow">CHOISIS UNE ACTIVITÉ</span><h2>Une envie ? Donne-toi quelques minutes.</h2><p>Les outils d’ancrage restent accessibles sans abonnement. Tu peux arrêter quand tu veux et revenir à ton parcours sans perdre tes données.</p>${premium?'':'<p><a href="/abonnement.html">Découvrir Premium — 29,99 € / an →</a></p>'}</section>`}

function zone(){return document.querySelector('#gameZone')}
function add(n){G.score+=n;save();const el=document.querySelector('#gameScore');if(el)el.textContent=G.score}
function memory(){const icons=['🌱','☀️','🌊','🍃','🌙','⭐'];const cards=[...icons,...icons].sort(()=>Math.random()-.5);G.memory={open:[],done:new Set(),moves:0};zone().innerHTML=`<span class="eyebrow">MEMORY</span><div class="row between"><h2>Retrouve les paires</h2><span class="tag" id="moves">0 coups</span></div><div class="memory-grid">${cards.map((x,i)=>`<button class="memory-card" data-mi="${i}" data-icon="${x}" aria-label="Carte ${i+1}">?</button>`).join('')}</div><p class="small">Chaque partie terminée rapporte 20 points détente.</p>`}
function memoryPick(btn){const m=G.memory,i=Number(btn.dataset.mi);if(!m||m.done.has(i)||m.open.includes(i)||m.open.length>=2)return;btn.textContent=btn.dataset.icon;btn.classList.add('open');m.open.push(i);if(m.open.length===2){m.moves++;document.querySelector('#moves').textContent=m.moves+' coups';const [a,b]=m.open,els=[...document.querySelectorAll('.memory-card')];if(els[a].dataset.icon===els[b].dataset.icon){m.done.add(a);m.done.add(b);m.open=[];els[a].classList.add('matched');els[b].classList.add('matched');if(m.done.size===els.length){add(20);setTimeout(()=>zone().insertAdjacentHTML('beforeend','<div class="game-win"><b>Partie terminée ✦ +20 points</b><button class="secondary" data-game="memory">Rejouer</button></div>'),250)}}else setTimeout(()=>{els[a].textContent='?';els[b].textContent='?';els[a].classList.remove('open');els[b].classList.remove('open');m.open=[]},650)}}
function reaction(){G.reaction={ready:false,start:0,timer:null};zone().innerHTML='<span class="eyebrow">RÉFLEXE ZEN</span><h2>Attends le signal…</h2><p>Quand la zone devient prête, touche-la le plus vite possible.</p><button id="reactionPad" class="reaction-pad">Attends…</button>';const wait=1000+Math.random()*3000;G.reaction.timer=setTimeout(()=>{G.reaction.ready=true;G.reaction.start=performance.now();const p=document.querySelector('#reactionPad');if(p){p.classList.add('ready');p.textContent='TOUCHE !'}},wait)}
function reactionHit(){const r=G.reaction;if(!r)return;if(!r.ready){clearTimeout(r.timer);zone().insertAdjacentHTML('beforeend','<p class="game-result">Trop tôt 🙂 Recommence tranquillement.</p>');return}const ms=Math.round(performance.now()-r.start);add(5);zone().innerHTML=`<span class="eyebrow">RÉFLEXE ZEN</span><h2>${ms} ms</h2><p>Bien joué. +5 points détente.</p><button class="secondary" data-game="reaction">Rejouer</button>`;G.reaction=null}
function taps(){G.taps={count:0,end:Date.now()+20000};zone().innerHTML='<span class="eyebrow">DÉFI 20 SECONDES</span><div class="row between"><h2>Attrape la cible</h2><b id="tapTime">20 s</b></div><div class="tap-arena"><button id="tapTarget" class="tap-target" aria-label="Cible">●</button></div><p id="tapCount">0 cible</p>';moveTarget();const tick=setInterval(()=>{if(!G.taps){clearInterval(tick);return}const left=Math.max(0,Math.ceil((G.taps.end-Date.now())/1000)),t=document.querySelector('#tapTime');if(t)t.textContent=left+' s';if(left<=0){clearInterval(tick);const n=G.taps.count;G.taps=null;add(Math.min(20,n));zone().innerHTML=`<span class="eyebrow">TERMINÉ</span><h2>${n} touches</h2><p>Tu viens de consacrer 20 secondes à autre chose. +${Math.min(20,n)} points.</p><button class="secondary" data-game="taps">Rejouer</button>`}},250)}
function moveTarget(){const b=document.querySelector('#tapTarget');if(!b)return;b.style.left=(5+Math.random()*78)+'%';b.style.top=(5+Math.random()*70)+'%'}
function tap(){if(!G.taps)return;G.taps.count++;const c=document.querySelector('#tapCount');if(c)c.textContent=G.taps.count+' touche'+(G.taps.count>1?'s':'');moveTarget()}

function stopArcade(){if(G.snake?.timer)clearInterval(G.snake.timer);if(G.blocks?.timer)clearInterval(G.blocks.timer);G.snake=null;G.blocks=null}
function snake(){stopArcade();const size=16;G.snake={size,body:[[7,8],[6,8],[5,8]],dir:[1,0],next:[1,0],food:[12,8],points:0};zone().innerHTML='<span class="eyebrow">SNAKE ZEN</span><div class="row between"><h2>Snake</h2><b id="snakeScore">0</b></div><canvas id="snakeCanvas" class="arcade-canvas" width="320" height="320" tabindex="0" aria-label="Jeu Snake"></canvas><div class="dpad"><span></span><button data-sdir="up">↑</button><span></span><button data-sdir="left">←</button><button data-sdir="down">↓</button><button data-sdir="right">→</button></div><p class="small">Flèches du clavier ou boutons tactiles. +1 point détente par fruit.</p>';drawSnake();G.snake.timer=setInterval(snakeTick,135);document.querySelector('#snakeCanvas')?.focus()}
function snakeDir(d){const s=G.snake;if(!s)return;const dirs={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]},n=dirs[d];if(n&&!(n[0]===-s.dir[0]&&n[1]===-s.dir[1]))s.next=n}
function snakeTick(){const s=G.snake;if(!s)return;s.dir=s.next;const h=s.body[0],n=[h[0]+s.dir[0],h[1]+s.dir[1]];if(n[0]<0||n[1]<0||n[0]>=s.size||n[1]>=s.size||s.body.some(p=>p[0]===n[0]&&p[1]===n[1])){clearInterval(s.timer);G.snake=null;zone().insertAdjacentHTML('beforeend','<div class="game-win"><b>Partie terminée</b><button class="secondary" data-game="snake">Rejouer</button></div>');return}s.body.unshift(n);if(n[0]===s.food[0]&&n[1]===s.food[1]){s.points++;add(1);do{s.food=[Math.floor(Math.random()*s.size),Math.floor(Math.random()*s.size)]}while(s.body.some(p=>p[0]===s.food[0]&&p[1]===s.food[1]));const el=document.querySelector('#snakeScore');if(el)el.textContent=s.points}else s.body.pop();drawSnake()}
function drawSnake(){const s=G.snake,c=document.querySelector('#snakeCanvas');if(!s||!c)return;const x=c.getContext('2d'),q=c.width/s.size;x.clearRect(0,0,c.width,c.height);x.fillStyle='#eef2ed';x.fillRect(0,0,c.width,c.height);x.fillStyle='#164e43';s.body.forEach(p=>x.fillRect(p[0]*q+1,p[1]*q+1,q-2,q-2));x.fillStyle='#b76e4b';x.beginPath();x.arc((s.food[0]+.5)*q,(s.food[1]+.5)*q,q*.34,0,Math.PI*2);x.fill()}
const SHAPES=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[0,1,1],[1,1,0]],[[1,1,0],[0,1,1]]];
function blocks(){stopArcade();G.blocks={w:10,h:16,board:Array.from({length:16},()=>Array(10).fill(0)),piece:null,x:0,y:0,score:0};newPiece();zone().innerHTML='<span class="eyebrow">BLOCS ZEN</span><div class="row between"><h2>Blocs</h2><b id="blockScore">0 lignes</b></div><canvas id="blocksCanvas" class="arcade-canvas blocks-canvas" width="250" height="400" tabindex="0" aria-label="Jeu de blocs"></canvas><div class="block-controls"><button data-bact="left">←</button><button data-bact="rotate">↻</button><button data-bact="down">↓</button><button data-bact="right">→</button></div><p class="small">Complète des lignes. Flèches ou commandes tactiles.</p>';drawBlocks();G.blocks.timer=setInterval(()=>blockAct('down'),520);document.querySelector('#blocksCanvas')?.focus()}
function newPiece(){const b=G.blocks;if(!b)return;b.piece=SHAPES[Math.floor(Math.random()*SHAPES.length)].map(r=>[...r]);b.x=Math.floor((b.w-b.piece[0].length)/2);b.y=0;if(collide(b,b.x,b.y,b.piece)){clearInterval(b.timer);setTimeout(()=>{if(zone())zone().insertAdjacentHTML('beforeend','<div class="game-win"><b>Partie terminée</b><button class="secondary" data-game="blocks">Rejouer</button></div>')},0)}}
function collide(b,nx,ny,p){return p.some((r,yy)=>r.some((v,xx)=>v&&(nx+xx<0||nx+xx>=b.w||ny+yy>=b.h||(ny+yy>=0&&b.board[ny+yy][nx+xx]))))}
function rotate(p){return p[0].map((_,i)=>p.map(r=>r[i]).reverse())}
function blockAct(a){const b=G.blocks;if(!b)return;if(a==='left'&&!collide(b,b.x-1,b.y,b.piece))b.x--;else if(a==='right'&&!collide(b,b.x+1,b.y,b.piece))b.x++;else if(a==='rotate'){const r=rotate(b.piece);if(!collide(b,b.x,b.y,r))b.piece=r}else if(a==='down'){if(!collide(b,b.x,b.y+1,b.piece))b.y++;else{b.piece.forEach((r,yy)=>r.forEach((v,xx)=>{if(v&&b.y+yy>=0)b.board[b.y+yy][b.x+xx]=1}));let lines=0;b.board=b.board.filter(r=>{if(r.every(Boolean)){lines++;return false}return true});while(b.board.length<b.h)b.board.unshift(Array(b.w).fill(0));if(lines){b.score+=lines;add(lines*5);const el=document.querySelector('#blockScore');if(el)el.textContent=b.score+' ligne'+(b.score>1?'s':'')}newPiece()}}drawBlocks()}
function drawBlocks(){const b=G.blocks,c=document.querySelector('#blocksCanvas');if(!b||!c)return;const x=c.getContext('2d'),q=c.width/b.w;x.fillStyle='#eef2ed';x.fillRect(0,0,c.width,c.height);const cell=(xx,yy,fill)=>{x.fillStyle=fill;x.fillRect(xx*q+1,yy*q+1,q-2,q-2)};b.board.forEach((r,y)=>r.forEach((v,xx)=>v&&cell(xx,y,'#6c8379')));b.piece.forEach((r,yy)=>r.forEach((v,xx)=>v&&cell(b.x+xx,b.y+yy,'#164e43')))}

function grounding(){zone().innerHTML='<span class="eyebrow">5 CHOSES</span><h2>Regarde autour de toi.</h2><p>Prends ton temps et trouve mentalement :</p><ol class="tool-steps"><li>5 choses que tu peux voir</li><li>4 choses que tu peux toucher</li><li>3 choses que tu peux entendre</li><li>2 choses que tu peux sentir</li><li>1 chose que tu apprécies maintenant</li></ol><button class="primary" data-ground-done>J’ai terminé</button>'}
export function initGames(){document.addEventListener('click',e=>{const upgrade=e.target.closest('[data-game-upgrade]')?.dataset.gameUpgrade;if(upgrade){location.href='/abonnement.html';return}const game=e.target.closest('[data-game]')?.dataset.game;if(game){if(!FREE_GAMES.has(game)&&!premiumAccess()){location.href='/abonnement.html';return}if(game==='memory')memory();if(game==='reaction')reaction();if(game==='taps')taps();if(game==='ground')grounding();if(game==='snake')snake();if(game==='blocks')blocks();return}const sd=e.target.closest('[data-sdir]')?.dataset.sdir;if(sd){snakeDir(sd);return}const ba=e.target.closest('[data-bact]')?.dataset.bact;if(ba){blockAct(ba);return}const mc=e.target.closest('.memory-card');if(mc){memoryPick(mc);return}if(e.target.closest('#reactionPad')){reactionHit();return}if(e.target.closest('#tapTarget')){tap();return}if(e.target.closest('[data-ground-done]')){add(10);zone().innerHTML='<span class="eyebrow">BIEN JOUÉ</span><h2>Tu as pris un moment pour revenir au présent.</h2><p>+10 points détente. Tu peux choisir une autre activité ou retourner à ton parcours.</p>'}})}

document.addEventListener('keydown',e=>{if(!document.querySelector('#gameZone'))return;if(G.snake&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();snakeDir({ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'}[e.key])}if(G.blocks&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();blockAct({ArrowUp:'rotate',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right'}[e.key])}});
