import {dayKey, parseDay, moveDay, dayDiff, dateLabel, esc} from './core.mjs';
import {validateTimelineDocument, timelineSnapshot} from './timeline-core.mjs';
import {createTimelineChart} from './timeline-chart.mjs';

const MODES={abstain:'Arrêter',reduce:'Réduire',observe:'Observer'};
const TRIGGERS=['Stress','Fatigue','Habitude','Ennui','Solitude','Soirées','Repas','Émotions'];
const nf=new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2});
const cf=new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:2});
const number=value=>Number.isFinite(value)?nf.format(value):'—';
const euros=value=>Number.isFinite(value)?cf.format(value):'—';
const clone=value=>JSON.parse(JSON.stringify(value));
const checked=value=>value?' checked':'';
const button=(action,text,extra='',className='secondary')=>`<button type="button" class="${className}" data-tl-action="${action}" ${extra}>${text}</button>`;
const field=(name,label,value='',extra='')=>`<label>${label}<input name="${name}" value="${esc(value??'')}" ${extra}></label>`;
const errorBox=()=>'<p class="tl-error" data-tl-error role="alert" hidden></p>';
const validNumber=value=>value!==''&&value!==null&&value!==undefined&&Number.isFinite(Number(value))?Number(value):'';
function monthsBefore(date,months){const d=parseDay(date),day=d.getDate();d.setDate(1);d.setMonth(d.getMonth()-months);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return dayKey(d);}
function safeDate(value,fallback){try{const raw=String(value||'').trim();let s=raw;if(!/^\d{4}-\d{2}-\d{2}$/.test(raw)){const instant=new Date(raw);if(!Number.isFinite(instant.getTime()))return fallback;s=dayKey(instant);}parseDay(s);return s>='1900-01-01'?s:fallback;}catch{return fallback;}}
function duration(n){return `${number(n)} jour${n===1?'':'s'}`;}

/** All writes go through one versioned save; the displayed goal never follows a consumption event. */
export function createTimelineUI(api){
 let forms=new WeakMap(),generation=0;
 const $=selector=>document.querySelector(selector);
 const get=()=>api.data();
 const today=()=>get().today||dayKey();
 const chart=createTimelineChart({data:()=>({document:get().document,checks:get().checks||[],today:today()}),render:()=>api.render(),openChange:date=>openChange(date),download:(...args)=>api.download(...args)});
 const snap=()=>timelineSnapshot(get().document,get().checks||[],today());
 const currentDoc=()=>get().document;
 function reset(){generation++;forms=new WeakMap();chart.reset();}
 function assertReady(){if(!get().ready)throw Error('Le suivi n’est pas encore chargé. Réessaie dans un instant.');}
 function readyView(){return '<section class="card tl-loading" role="status"><h2>Chargement de ton suivi…</h2><p>Tes repères apparaîtront ici.</p></section>';}
 function welcome(){return `<div class="greeting tl-heading"><h1>Ton point de départ</h1><p>Quelques repères pour voir tes progrès.</p></div><section class="card tl-welcome"><span class="tl-welcome-mark" aria-hidden="true">↗</span><h2>Tu as déjà commencé ?<br>Ton parcours compte déjà.</h2><p>Indique ta situation et sa date de début.</p><div class="tl-welcome-points"><span>Une date</span><span>Ton rythme</span><span>Tes économies</span></div>${button('setup','Configurer mon suivi','','primary full')}<p class="tl-caption">Pas de bilan quotidien obligatoire.</p></section>`;}
 function home(){
  if(!get().ready)return readyView();
  if(!currentDoc())return welcome();
  const d=currentDoc(),s=snap(),c=s.current,sober=c.state==='abstinent',saved=s.summary?.saved;
  return `<div class="greeting tl-heading"><div><h1>Un pas après l’autre.</h1><p>Mon objectif : ${esc(MODES[d.goal.mode])}</p></div>${button('settings','Mes repères','','text')}</div>
   <div class="tl-home-grid"><section class="card tl-hero"><div class="tl-hero-top"><span class="tag">${sober?'Période d’arrêt':'Mon rythme actuel'}</span>${button('date','Modifier la date','','tl-hero-edit')}</div>
   <div class="tl-hero-value">${number(sober?s.currentStreak:c.units_week)}<span>${sober?'jour'+(s.currentStreak===1?'':'s'):'verres / semaine'}</span></div>
   <p class="tl-hero-label">${sober?'depuis la dernière consommation déclarée':'estimés pour cette période'}</p>
   <div class="tl-hero-date"><span>${sober?'Arrêt déclaré le':'Rythme déclaré depuis le'}</span><b>${dateLabel(c.started_on)}</b></div>
   <p class="tl-caption">${sober?'Ton arrêt est compté jusqu’à une reprise déclarée.':'Actualise ton rythme quand il change.'}</p>
   </section><section class="card tl-earned"><h2>Ce que tu as parcouru</h2><div class="tl-earned-grid"><div><strong>${number(s.totalSoberDays)}</strong><span>jours sans alcool cumulés</span></div><div><strong>${number(s.bestStreak)}</strong><span>jours pour ton meilleur arrêt</span></div></div><div class="tl-money ${saved<0?'tl-negative':''}"><strong>${euros(saved<0?-saved:saved)}</strong><span>${saved<0?'de dépenses supplémentaires estimées':'d’économies estimées'}</span></div>${button('progress','Voir mes courbes →','','secondary full')}</section></div>
   <div class="tl-actions">${button('occasion','<span aria-hidden="true">＋</span><b>J’ai consommé</b><small>Noter une occasion</small>','','tl-action-card')}${button('change','<span aria-hidden="true">↔</span><b>Mon rythme a changé</b><small>Arrêt, reprise ou réduction</small>','','tl-action-card')}${button('history','<span aria-hidden="true">↗</span><b>Mon historique</b><small>Retrouver mes étapes</small>','','tl-action-card')}</div>
   <div class="tl-home-bottom"><p class="tl-caption">Tes arrêts précédents et ton objectif restent conservés.</p><div class="row">${button('help','Besoin de soutien ?','','text')}${button('games','Faire une pause','','text')}</div></div>
   ${d.goal.why?`<section class="card tl-why"><span class="eyebrow">MON POURQUOI</span><p>${esc(d.goal.why)}</p></section>`:''}`;
 }
 function view(){if(!get().ready)return readyView();if(!currentDoc())return welcome();return `<div class="greeting tl-heading"><div><h1>Mes progrès</h1><p>Mon objectif : ${esc(MODES[currentDoc().goal.mode])}</p></div>${button('change','+ Un changement','','primary')}</div>${chart.view()}${history(true)}`;}
 function journey(){if(!get().ready)return readyView();if(!currentDoc())return welcome();return `<div class="greeting tl-heading"><div><h1>Mon parcours</h1><p>Chaque période fait partie de ton histoire.</p></div>${button('change','+ Une période','','primary')}</div>${achievements()}${history(false)}`;}
 function achievements(){const s=snap();return `<section class="card tl-achievements"><h2>Mes acquis</h2><div class="tl-achievement-grid"><div><strong>${number(s.totalSoberDays)}</strong><span>jours sans alcool cumulés</span></div><div><strong>${number(s.bestStreak)}</strong><span>jours pour mon meilleur arrêt</span></div><div><strong>${number(api.programCount?.()||0)}</strong><span>étapes personnelles terminées</span></div></div><p class="tl-caption">Une consommation n’efface pas les jours déjà parcourus.</p></section>`;}
 function history(collapsed=false){
  const d=currentDoc(),s=snap(),events=[...d.events].sort((a,b)=>a.started_on.localeCompare(b.started_on)),occasions=[...d.occasions].sort((a,b)=>b.date.localeCompare(a.date));
  const rows=events.map((event,i)=>{const end=i+1<events.length?moveDay(events[i+1].started_on,-1):null;return `<li class="tl-history-event"><span class="tl-history-dot ${event.state==='abstinent'?'is-abstinent':''}" aria-hidden="true"></span><div><div class="tl-history-top"><span class="tag">${event.state==='abstinent'?'Arrêt':'Consommation'}</span>${!end?'<small>En cours</small>':''}</div><h3>${dateLabel(event.started_on)}</h3><p>${end?'Jusqu’au '+dateLabel(end):'Depuis '+duration(dayDiff(today(),event.started_on))}</p><span class="tl-caption">${number(event.units_week)} verres / semaine · ${euros(event.cost_week)} / semaine · estimés</span>${event.note?`<p class="tl-event-note">${esc(event.note)}</p>`:''}</div>${button('edit-event','Modifier',`data-tl-id="${esc(event.id)}"`,'text')}</li>`;}).reverse().join('');
  const stops=(s.bestPeriods||[]).slice(0,6).map(p=>`<li><strong>${duration(p.days)}</strong><span>${dateLabel(p.start)}${p.end?' → '+dateLabel(p.end):''}${p.ongoing?' · en cours':''}</span></li>`).join('');
  const body=`<p class="tl-caption">Modifier une date recalcule les statistiques. Les autres périodes restent enregistrées.</p><ol class="tl-history-list">${rows}</ol>${button('change','+ Ajouter un changement passé','','secondary')}<details class="tl-details"><summary>Mes arrêts sans alcool <span>${s.bestPeriods?.length||0}</span></summary>${stops?`<ul class="tl-stop-list">${stops}</ul>`:'<p class="tl-caption">Le premier jour complet de ton arrêt apparaîtra ici.</p>'}</details><details class="tl-details"><summary>Mes consommations ponctuelles <span>${occasions.length}</span></summary>${occasions.length?`<ul class="tl-occasion-list">${occasions.map(o=>`<li><div><b>${dateLabel(o.date)}</b><span>${number(o.units)} verres · ${euros(o.cost)}</span></div>${button('edit-occasion','Modifier',`data-tl-date="${o.date}"`,'text')}</li>`).join('')}</ul>`:'<p class="tl-caption">Aucune occasion déclarée.</p>'}${button('occasion','+ Noter une occasion','','text')}</details>`;
  return collapsed?`<details class="card tl-history tl-details tl-section"><summary>Mon historique <span>${events.length} période${events.length===1?'':'s'}</span></summary>${body}</details>`:`<section class="card tl-history tl-section"><div class="tl-section-heading"><h2>Mes périodes</h2>${button('settings','Mes objectifs','','text')}</div>${body}</section>`;
 }
 function settingsSummary(){if(!get().ready)return readyView();if(!currentDoc())return `<section class="tl-settings-summary"><p>Ajoute ta date et tes premiers repères.</p>${button('setup','Configurer mon suivi','','primary')}</section>`;const d=currentDoc(),s=snap();return `<section class="tl-settings-summary"><div><span class="tl-caption">Mon objectif</span><b>${esc(MODES[d.goal.mode])}</b></div><div><span class="tl-caption">${s.current.state==='abstinent'?'Arrêt déclaré le':'Rythme actuel depuis le'}</span><b>${dateLabel(s.current.started_on)}</b></div><div class="row">${button('settings','Objectif et préférences','','secondary')}${button('history','Mon historique','','text')}</div></section>`;}

 function dateFields(value,{min='1900-01-01',max=today(),shortcuts=true}={}){return `<fieldset class="tl-fieldset"><legend>Depuis quand ?</legend>${shortcuts?`<div class="tl-shortcuts" aria-label="Dates rapides">${[[7,'7 jours'],[14,'14 jours'],['month','1 mois']].map(([n,t])=>{const date=n==='month'?monthsBefore(today(),1):moveDay(today(),-n);return button('date-shortcut',t,`data-tl-date="${date}" ${date<min||date>max?'disabled':''}`,'tl-chip');}).join('')}</div>`:''}${field('started_on','Date de début',value,`type="date" required min="${min}" max="${max}" data-tl-change="date"`)}<p class="tl-caption tl-date-preview" data-tl-date-preview aria-live="polite"></p></fieldset>`;}
 function stateFields(state,units='',cost=0){
  const soberCost=state==='abstinent'?cost:0;
  return `<fieldset class="tl-fieldset"><legend>Ma situation</legend><div class="tl-choices tl-choices-two">${[['abstinent','Sans alcool'],['drinking','Je consomme']].map(([value,label])=>`<label class="tl-choice"><input type="radio" name="state" value="${value}" required data-tl-change="state"${checked(state===value)}><span>${label}</span></label>`).join('')}</div><div data-tl-abstinent hidden><div class="tl-zero"><div><strong>0</strong><span>verre / semaine</span></div><div><strong data-tl-zero-cost>${euros(validNumber(soberCost)||0)}</strong><span>d’alcool / semaine</span></div></div><details class="tl-details tl-budget-detail" ${soberCost>0?'open':''}><summary>J’ai encore des achats d’alcool</summary>${field('abstinent_cost_week','Budget alcool estimé / semaine (€)',soberCost,'type="number" min="0" max="7000000" step="0.01" inputmode="decimal" data-tl-change="sober-cost"')}</details></div><div data-tl-drinking hidden><div class="two-fields">${field('current_units_week','Verres standard / semaine',state==='drinking'?units:'','type="number" min="0.01" max="7000" step="0.01" inputmode="decimal" placeholder="Ex. 10"')}${field('current_cost_week','Budget alcool / semaine (€)',state==='drinking'?cost:'','type="number" min="0" max="7000000" step="0.01" inputmode="decimal" placeholder="Ex. 30"')}</div><p class="tl-caption">Une moyenne estimée. Pour 0 verre, choisis « Sans alcool ».</p></div></fieldset>`;
 }
 function baselineFields(baseline){return `<fieldset class="tl-fieldset tl-baseline"><legend>Mes anciens repères</legend><p class="tl-caption">Avant mon changement, en moyenne :</p><div class="two-fields">${field('baseline_units_week','Verres standard / semaine',baseline.units_week,'type="number" required min="0" max="7000" step="0.01" inputmode="decimal" placeholder="Ex. 20"')}${field('baseline_cost_week','Budget alcool / semaine (€)',baseline.cost_week,'type="number" required min="0" max="7000000" step="0.01" inputmode="decimal" placeholder="Ex. 60"')}</div>${field('baseline_started_on','Ces habitudes étaient valables depuis le',baseline.started_on,`type="date" required min="1900-01-01" max="${today()}"`)}<p class="tl-caption">Ces estimations servent de comparaison à partir de cette date.</p></fieldset>`;}
 function goalChoices(goal){return `<fieldset class="tl-fieldset"><legend>Mon objectif</legend><div class="tl-choices tl-choices-three">${Object.entries(MODES).map(([value,label])=>`<label class="tl-choice"><input type="radio" name="goal_mode" value="${value}" required data-tl-change="goal"${checked(goal.mode===value)}><span>${label}</span></label>`).join('')}</div><div data-tl-goal-confirm hidden><label class="checklabel tl-confirm"><input type="checkbox" name="confirm_goal_change"> Je choisis de modifier mon objectif d’arrêt.</label></div></fieldset>`;}
 function optionalGoalFields(goal){
  const triggers=[...new Set([...TRIGGERS,...(goal.triggers||[])])];
  return `<details class="tl-details tl-preferences"><summary>Objectifs et préférences <span>facultatif</span></summary><label>Mon pourquoi<textarea name="why" rows="2" maxlength="1000" placeholder="Ce que je veux retrouver…">${esc(goal.why||'')}</textarea></label><label>Mon prochain pas<textarea name="planned_action" rows="2" maxlength="500" placeholder="Une petite action qui me convient…">${esc(goal.planned_action||'')}</textarea></label><fieldset class="tl-fieldset"><legend>Mes situations à anticiper</legend><div class="tl-trigger-choices">${triggers.map(t=>`<label class="tl-trigger"><input type="checkbox" name="triggers" value="${esc(t)}"${checked((goal.triggers||[]).includes(t))}><span>${esc(t)}</span></label>`).join('')}</div></fieldset>${field('target_on','Date de mon objectif personnel',goal.target_on||'','type="date" min="1900-01-01" max="2100-12-31"')}<label class="checklabel tl-confirm"><input type="checkbox" name="support_first" data-tl-change="goal"${checked(goal.support_first)}> Je privilégie un accompagnement professionnel.</label><div data-tl-limits hidden><p class="tl-caption">Mes limites personnelles, sans quantité à atteindre.</p><div class="two-fields">${field('weekly_limit','Maximum / semaine (verres)',goal.weekly_limit??'','type="number" min="0" max="7000" step="0.01" inputmode="decimal" placeholder="Facultatif"')}${field('daily_limit','Maximum / jour (verres)',goal.daily_limit??'','type="number" min="0" max="1000" step="0.01" inputmode="decimal" placeholder="Facultatif"')}</div></div></details>`;
 }
 function supportNote(){return '<p class="tl-safety">En cas de symptômes de manque, demande une aide médicale. Si tu as bu, ne conduis pas.</p>';}
 function attach(formId,doc,extra={}){const f=$('#'+formId);if(!f)return;forms.set(f,{doc:doc?clone(doc):null,versions:clone(api.versions()),generation,...extra});syncForm(f);}
 function seedGoal(){const chapters=get().chapters||[],last=[...chapters].sort((a,b)=>String(a.effective_on||'').localeCompare(String(b.effective_on||''))).at(-1)||{};return {mode:MODES[last.mode]?last.mode:'abstain',weekly_limit:last.weekly_limit??null,daily_limit:last.daily_limit??null,target_on:null,why:get().journey?.why_text||'',triggers:[],support_first:!!last.support_first,planned_action:last.planned_action||''};}
 function openSetup(){
  assertReady();if(currentDoc())return openSettings();const data=get(),goal=seedGoal(),baseline={started_on:monthsBefore(today(),12),units_week:validNumber(data.settings?.baseline_units_week),cost_week:validNumber(data.settings?.baseline_cost_week??data.journey?.weekly_spend_estimate)};
  const initialDate=safeDate(data.journey?.started_at,today());
  api.modal('Mon point de départ',`<form id="tlStartForm" class="tl-form" data-tl-form="start">${goalChoices(goal)}${stateFields('',null,0)}${dateFields(initialDate>today()?today():initialDate)}${baselineFields(baseline)}${optionalGoalFields(goal)}<label class="checklabel tl-confirm"><input type="checkbox" name="confirm_periods" required> Je confirme ces dates et ces estimations, y compris les zéros affichés. Les jours sans bilan seront estimés à partir de ces repères.</label><p class="tl-caption">1 verre standard = 10 g d’alcool pur.</p>${errorBox()}<button type="submit" class="primary full">Commencer mon suivi</button>${supportNote()}</form>`);
  attach('tlStartForm',null,{originalMode:data.chapters?.length?goal.mode:null});
 }
 function openSettings(){
  assertReady();if(!currentDoc())return openSetup();const d=currentDoc();
  api.modal('Mes objectifs et repères',`<form id="tlSettingsForm" class="tl-form" data-tl-form="settings">${goalChoices(d.goal)}${optionalGoalFields(d.goal)}<details class="tl-details"><summary>Mes anciens repères</summary>${baselineFields(d.baseline)}<p class="tl-caption">Une correction recalcule les comparaisons de tout mon parcours.</p></details><label class="checklabel tl-confirm"><input type="checkbox" name="confirm_periods" required> Je confirme mes repères et leurs estimations.</label>${errorBox()}<button type="submit" class="primary full">Enregistrer mes choix</button><div class="tl-modal-links">${button('date','Modifier la date actuelle','','text')}${button('history','Voir mon historique','','text')}</div>${supportNote()}</form>`);
  attach('tlSettingsForm',d,{originalMode:d.goal.mode});
 }
 function openDate(){assertReady();if(!currentDoc())return openSetup();const c=snap().current.event;openEvent(c.started_on,c.id);}
 function openChange(date){assertReady();if(!currentDoc())return openSetup();openEvent(date||today());}
 function openEvent(date,id){
  const d=currentDoc(),ordered=[...d.events].sort((a,b)=>a.started_on.localeCompare(b.started_on)),existing=id?ordered.find(e=>e.id===id):ordered.find(e=>e.started_on===date),editId=existing?.id||null;
  const previous=ordered.filter(e=>e.id!==editId&&e.started_on<(existing?.started_on||date)).at(-1),next=ordered.find(e=>e.id!==editId&&e.started_on>(existing?.started_on||date));
  const min=previous?moveDay(previous.started_on,1):'1900-01-01',max=next?moveDay(next.started_on,-1):today(),active=existing||previous||ordered[0],state=existing?.state||active.state;
  api.modal(existing?'Modifier cette période':'Mon rythme a changé',`<form id="tlEventForm" class="tl-form" data-tl-form="event"><p class="tl-caption">Ton objectif reste : ${esc(MODES[d.goal.mode])}.</p>${stateFields(state,active.units_week,active.cost_week)}${dateFields(existing?.started_on||date,{min,max})}${existing?baselineFields(d.baseline):''}<details class="tl-details"><summary>Ajouter une note <span>facultatif</span></summary><label>Mon repère<textarea name="note" rows="2" maxlength="300">${esc(existing?.note||'')}</textarea></label></details><label class="checklabel tl-confirm"><input type="checkbox" name="confirm_periods" required> Je confirme cette période et les estimations affichées, y compris les valeurs à zéro.</label>${errorBox()}<button type="submit" class="primary full">${existing?'Enregistrer la correction':'Enregistrer ce changement'}</button>${supportNote()}</form>`);
  attach('tlEventForm',d,{editId,min,max,originalMode:d.goal.mode});
 }
 function openOccasion(date){
  assertReady();if(!currentDoc())return openSetup();const d=currentDoc(),chosen=date||today(),existing=d.occasions.find(o=>o.date===chosen);
  api.modal(existing?'Modifier cette occasion':'J’ai consommé',`<form id="tlOccasionForm" class="tl-form" data-tl-form="occasion"><p class="tl-caption">Ton objectif et tes arrêts précédents restent conservés.</p>${field('date','Date',chosen,`type="date" required min="${d.baseline.started_on}" max="${today()}" data-tl-change="occasion-date"`)}<div class="two-fields">${field('units','Verres ce jour-là',existing?.units??'','type="number" required min="0.01" max="1000" step="0.01" inputmode="decimal" placeholder="Ex. 2"')}${field('cost','Dépenses ce jour-là (€)',existing?.cost??'','type="number" required min="0" max="1000000" step="0.01" inputmode="decimal" placeholder="Ex. 0"')}</div><p class="tl-caption" data-tl-occasion-hint>${existing?'Les nouvelles valeurs remplaceront celles de cette date.':'Indique le total de la journée. 1 verre standard = 10 g d’alcool pur.'}</p>${errorBox()}<button type="submit" class="primary full">Enregistrer l’occasion</button><div class="tl-modal-links">${button('change','Mon rythme a changé durablement','','text')}${existing?button('remove-occasion-open','Cette déclaration est une erreur','','text tl-remove'):''}</div>${supportNote()}</form>`);
  attach('tlOccasionForm',d,{editId:existing?.id||null,originalDate:existing?.date||null});
 }
 function openRemoveOccasion(f){
  assertReady();const context=forms.get(f);if(!context||context.generation!==generation)throw Error('Rouvre cette occasion depuis ton historique.');
  const occasion=context.doc.occasions.find(o=>o.id===context.editId);if(!occasion)throw Error('Rouvre cette occasion depuis ton historique.');
  api.modal('Annuler une déclaration erronée',`<form id="tlRemoveOccasionForm" class="tl-form" data-tl-form="remove-occasion"><div class="tl-correction-summary"><b>${dateLabel(occasion.date)}</b><span>${number(occasion.units)} verres · ${euros(occasion.cost)}</span></div><p>Cette déclaration sera retirée. Les compteurs et les courbes seront recalculés.</p><label class="checklabel tl-confirm"><input type="checkbox" name="confirm_remove" required> Je confirme que cette consommation a été déclarée par erreur.</label>${errorBox()}<button type="submit" class="primary full">Annuler cette déclaration</button><div class="tl-modal-links">${button('edit-occasion','Revenir sans annuler',`data-tl-date="${occasion.date}"`,'text')}</div></form>`);
  attach('tlRemoveOccasionForm',context.doc,{editId:occasion.id,versions:clone(context.versions),generation:context.generation});
 }
 function syncForm(f){
  const c=forms.get(f);if(!c)return;
  if(f.elements.state){const state=f.elements.state.value,sober=state==='abstinent',drinking=state==='drinking';f.querySelector('[data-tl-abstinent]').hidden=!sober;f.querySelector('[data-tl-drinking]').hidden=!drinking;f.elements.abstinent_cost_week.disabled=!sober;f.elements.abstinent_cost_week.required=sober;for(const key of ['current_units_week','current_cost_week']){f.elements[key].disabled=!drinking;f.elements[key].required=drinking;}}
  if(f.elements.goal_mode){const goal=f.elements.goal_mode.value,changed=c.originalMode==='abstain'&&goal!=='abstain';f.querySelector('[data-tl-goal-confirm]').hidden=!changed;f.elements.confirm_goal_change.required=changed;const targets=goal==='reduce'&&!f.elements.support_first?.checked;f.querySelector('[data-tl-limits]').hidden=!targets;for(const key of ['weekly_limit','daily_limit'])f.elements[key].disabled=!targets;}
  if(f.elements.started_on){const target=f.querySelector('[data-tl-date-preview]');try{const days=dayDiff(today(),f.elements.started_on.value);target.textContent=days===0?'Cette période commence aujourd’hui.':`${duration(days)} depuis cette date.`;}catch{target.textContent='';}}
  if(f.elements.abstinent_cost_week){const output=f.querySelector('[data-tl-zero-cost]');output.textContent=euros(validNumber(f.elements.abstinent_cost_week.value)||0);}
 }
 function baselineFrom(data){return {started_on:String(data.get('baseline_started_on')||''),units_week:requiredNumber(data.get('baseline_units_week'),'Ancienne consommation',0,7000),cost_week:requiredNumber(data.get('baseline_cost_week'),'Ancien budget alcool',0,7000000)};}
 function requiredNumber(raw,label,min,max){if(String(raw??'').trim()==='')throw Error(`${label} : renseigne une estimation.`);const n=Number(raw);if(!Number.isFinite(n)||n<min||n>max)throw Error(`${label} : choisis un nombre entre ${min} et ${max}.`);return Math.round(n*100)/100;}
 function optionalNumber(raw,label,max){return raw===null||String(raw).trim()===''?null:requiredNumber(raw,label,0,max);}
 function goalFrom(data,context){
  const mode=String(data.get('goal_mode')||'');if(!MODES[mode])throw Error('Choisis ton objectif.');if(context.originalMode==='abstain'&&mode!=='abstain'&&!data.get('confirm_goal_change'))throw Error('Confirme ton choix de modifier ton objectif d’arrêt.');
  const support_first=!!data.get('support_first'),limits=mode==='reduce'&&!support_first;
  return {mode,weekly_limit:limits?optionalNumber(data.get('weekly_limit'),'Limite hebdomadaire',7000):null,daily_limit:limits?optionalNumber(data.get('daily_limit'),'Limite quotidienne',1000):null,target_on:String(data.get('target_on')||'')||null,why:String(data.get('why')||'').trim(),triggers:data.getAll('triggers').map(String),support_first,planned_action:String(data.get('planned_action')||'').trim()};
 }
 function eventFrom(data,id){const state=String(data.get('state')||'');if(!['abstinent','drinking'].includes(state))throw Error('Choisis ta situation pour cette période.');return {id:id||crypto.randomUUID(),started_on:String(data.get('started_on')||''),state,units_week:state==='abstinent'?0:requiredNumber(data.get('current_units_week'),'Consommation hebdomadaire',0.01,7000),cost_week:requiredNumber(data.get(state==='abstinent'?'abstinent_cost_week':'current_cost_week'),'Budget alcool',0,7000000),note:String(data.get('note')||'').trim()};}
 function validateDates(doc){const earliest=[...doc.events.map(e=>e.started_on),...doc.occasions.map(o=>o.date)].sort()[0];if(earliest&&doc.baseline.started_on>earliest)throw Error(`Les anciens repères doivent commencer au plus tard le ${dateLabel(earliest)}. Corrige « Ces habitudes étaient valables depuis le ». `);}
 function showError(f,error){const out=f.querySelector('[data-tl-error]');if(out){out.hidden=false;out.textContent=String(error?.message||error||'L’enregistrement a échoué.');out.scrollIntoView({block:'nearest'});}}
 async function saveForm(f,data){
  const context=forms.get(f);if(!context||context.generation!==generation)throw Error('Rouvre ce formulaire pour actualiser ton suivi.');
  if(!['occasion','remove-occasion'].includes(f.dataset.tlForm)&&!data.get('confirm_periods'))throw Error('Confirme les périodes et leurs estimations.');
  let doc=context.doc?clone(context.doc):null;
  if(f.dataset.tlForm==='start'){let timezone='Europe/Paris';try{timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||timezone;}catch{}doc={schema_version:1,timezone,baseline:baselineFrom(data),events:[eventFrom(data)],occasions:[],goal:goalFrom(data,context)};}
  if(f.dataset.tlForm==='settings'){doc.baseline=baselineFrom(data);doc.goal=goalFrom(data,context);}
  if(f.dataset.tlForm==='event'){const event=eventFrom(data,context.editId);if(event.started_on<context.min||event.started_on>context.max)throw Error('Cette date chevauche une autre période. Choisis une date entre les périodes voisines.');if(context.editId){doc.events=doc.events.map(e=>e.id===context.editId?event:e);doc.baseline=baselineFrom(data);}else doc.events.push(event);}
  if(f.dataset.tlForm==='occasion'){
   const date=String(data.get('date')||''),sameDay=doc.occasions.find(o=>o.date===date);
   if(context.editId&&sameDay&&sameDay.id!==context.editId)throw Error('Une occasion existe déjà à cette date. Ouvre-la dans ton historique pour modifier son total.');
   const id=sameDay?.id||context.editId||crypto.randomUUID();
   const occasion={id,date,units:requiredNumber(data.get('units'),'Verres ce jour-là',0.01,1000),cost:requiredNumber(data.get('cost'),'Dépenses ce jour-là',0,1000000)};
   // Correcting a day is replacement, never an addition to a previous total.
   doc.occasions=doc.occasions.filter(o=>o.date!==date&&(!context.editId||o.id!==context.editId));doc.occasions.push(occasion);
  }
  if(f.dataset.tlForm==='remove-occasion'){if(!data.get('confirm_remove'))throw Error('Confirme que cette déclaration était une erreur.');doc.occasions=doc.occasions.filter(o=>o.id!==context.editId);}
  validateDates(doc);const validated=validateTimelineDocument(doc,today());
  const saved=await api.save(validated,context.versions);
  if(saved!==true||context.generation!==generation)return;
  if(document.contains(f))api.closeModal();api.render();
  api.notify(f.dataset.tlForm==='start'?'Ton suivi est prêt. Ton parcours est déjà pris en compte.':f.dataset.tlForm==='occasion'?'Occasion enregistrée. Tes acquis restent conservés.':f.dataset.tlForm==='remove-occasion'?'Déclaration annulée. Tes progrès ont été recalculés.':'Repères enregistrés. Tes progrès ont été recalculés.');
 }
 const actions={
  setup:openSetup,settings:openSettings,date:openDate,occasion:()=>openOccasion(),change:()=>openChange(),
  progress:()=>{api.closeModal();api.openProgress();},history:()=>{api.closeModal();api.openPage('journey');},games:()=>api.openPage('games'),
  help:()=>{api.modal('Un peu de soutien',`<p>Tu peux faire une pause et contacter une personne de confiance.</p><p class="tl-safety">En cas de symptômes de manque, demande une aide médicale. En cas d’urgence, appelle le 15 ou le 112.</p><div class="row"><a class="secondary tl-support-link" href="tel:0980980930">Alcool Info Service</a><a class="secondary tl-support-link" href="tel:112">112 · Urgence</a></div>`);},
  'edit-event':b=>{assertReady();const event=currentDoc()?.events.find(e=>e.id===b.dataset.tlId);if(!event)throw Error('Cette période n’est plus disponible.');openEvent(event.started_on,event.id);},
  'edit-occasion':b=>openOccasion(b.dataset.tlDate),
  'remove-occasion-open':b=>openRemoveOccasion(b.closest('form')),
  'date-shortcut':b=>{const f=b.closest('form');f.elements.started_on.value=b.dataset.tlDate;syncForm(f);}
 };
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-tl-action]');if(!b||b.disabled)return;const action=actions[b.dataset.tlAction];if(!action)return;e.preventDefault();e.stopImmediatePropagation();b.disabled=true;try{await action(b);}catch(error){const f=b.closest('form');if(f)showError(f,error);else api.notify(String(error?.message||error));}finally{b.disabled=false;}},true);
 document.addEventListener('change',e=>{const f=e.target.closest('form[data-tl-form]');if(!f)return;if(e.target.dataset.tlChange==='occasion-date'){const context=forms.get(f),existing=context?.doc?.occasions.find(o=>o.date===f.elements.date.value),hint=f.querySelector('[data-tl-occasion-hint]');hint.textContent=existing?'Les nouvelles valeurs remplaceront celles de cette date.':'Indique le total de la journée. 1 verre standard = 10 g d’alcool pur.';if(existing){f.elements.units.value=existing.units;f.elements.cost.value=existing.cost;}}syncForm(f);});
 document.addEventListener('input',e=>{const f=e.target.closest('form[data-tl-form]');if(f&&['date','sober-cost'].includes(e.target.dataset.tlChange))syncForm(f);});
 document.addEventListener('submit',async e=>{const f=e.target;if(!f.matches('form[data-tl-form]'))return;e.preventDefault();e.stopImmediatePropagation();const submit=e.submitter||f.querySelector('button[type="submit"]');if(submit?.disabled)return;const data=new FormData(f);if(submit)submit.disabled=true;const out=f.querySelector('[data-tl-error]');if(out)out.hidden=true;try{await saveForm(f,data);}catch(error){showError(f,error);}finally{if(submit)submit.disabled=false;}},true);
 return {home,view,journey,settingsSummary,openSettings,openDate,openOccasion,openChange,reset};
}
